import './globals.css' //this is the default layout for all the pages 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-sans text-textColor">{children}</body>
    </html>
  )
}
